# Multi Target Classification

In [1]:
#hide
!pip install -Uqq fastbook
import fastbook
fastbook.setup_book()

In [2]:
#hide
from fastbook import *

In [3]:
torch.random.manual_seed(42);

acts = torch.randn((6,2))*2


In [4]:
targ = tensor([0,1,0,1,1,0])
sm_acts = torch.softmax(acts, dim=1)
sm_acts

tensor([[0.6025, 0.3975],
        [0.5021, 0.4979],
        [0.1332, 0.8668],
        [0.9966, 0.0034],
        [0.5959, 0.4041],
        [0.3661, 0.6339]])

In [5]:
idx = range(6)
sm_acts[idx, targ]       #identical to torch.where for more tha two values


tensor([0.6025, 0.4979, 0.1332, 0.0034, 0.4041, 0.3661])

### for row1(label 0), it picks from the 0th index, i.e, 0.6, for the second row(label 1), it picks the first from the first row, i.e 0.49

In [6]:
import pandas as pd

In [7]:
df = pd.DataFrame(sm_acts, columns = ['3','7'])
df['targ'] = targ
df['idx'] = idx
df['loss'] = sm_acts[idx,targ]
df

3         7  targ  idx      loss
0  0.602469  0.397531     0    0  0.602469
1  0.502065  0.497935     1    1  0.497935
2  0.133188  0.866811     0    2  0.133188
3  0.996640  0.003360     1    3  0.003360
4  0.595949  0.404051     1    4  0.404051
5  0.366118  0.633882     0    5  0.366118

Looking at this table, you can see that the final column can be calculated by taking the targ and idx columns as indices into the two-column matrix containing the 3 and 7 columns. That's what sm_acts[idx, targ] is actually doing.



In [8]:
-sm_acts[idx,targ]

tensor([-0.6025, -0.4979, -0.1332, -0.0034, -0.4041, -0.3661])

In [9]:
F.nll_loss(sm_acts,targ,reduction='none')

tensor([-0.6025, -0.4979, -0.1332, -0.0034, -0.4041, -0.3661])